#!/usr/bin/env bun
/**
 * This script generates an embedded assets module from the frontend build.
 * It reads all files from frontend/dist and creates a TypeScript module
 * that exports them as base64-encoded strings, which get compiled into the binary.
 */

import fs from 'fs';
import path from 'path';

const FRONTEND_DIST = path.join(import.meta.dir, '../../frontend/dist');
const OUTPUT_FILE = path.join(import.meta.dir, '../src/embedded-assets.ts');

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.eot': 'application/vnd.ms-fontobject',
};

function getMimeType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  return MIME_TYPES[ext] || 'application/octet-stream';
}

interface AssetEntry {
  path: string;
  contentType: string;
  content: string; // base64 encoded
}

function collectFiles(dir: string, prefix: string = ''): AssetEntry[] {
  const entries: AssetEntry[] = [];
  
  if (!fs.existsSync(dir)) {
    console.error(`Frontend dist directory not found: ${dir}`);
    console.error('Run "bun run build:frontend" first.');
    process.exit(1);
  }
  
  const items = fs.readdirSync(dir, { withFileTypes: true });
  
  for (const item of items) {
    const fullPath = path.join(dir, item.name);
    const urlPath = prefix ? `${prefix}/${item.name}` : `/${item.name}`;
    
    if (item.isDirectory()) {
      entries.push(...collectFiles(fullPath, urlPath));
    } else {
      const content = fs.readFileSync(fullPath);
      entries.push({
        path: urlPath,
        contentType: getMimeType(item.name),
        content: content.toString('base64'),
      });
    }
  }
  
  return entries;
}

function generateModule(assets: AssetEntry[]): string {
  const lines: string[] = [
    '// AUTO-GENERATED FILE - DO NOT EDIT',
    '// Generated by scripts/embed-assets.ts',
    '// Run "bun run embed" to regenerate',
    '',
    'export interface EmbeddedAsset {',
    '  contentType: string;',
    '  content: string; // base64 encoded',
    '}',
    '',
    'export const EMBEDDED_ASSETS: Record<string, EmbeddedAsset> = {',
  ];
  
  for (const asset of assets) {
    lines.push(`  ${JSON.stringify(asset.path)}: {`);
    lines.push(`    contentType: ${JSON.stringify(asset.contentType)},`);
    lines.push(`    content: ${JSON.stringify(asset.content)},`);
    lines.push('  },');
  }
  
  lines.push('};');
  lines.push('');
  
  return lines.join('\n');
}

// Main
console.log('📦 Embedding frontend assets...');
const assets = collectFiles(FRONTEND_DIST);
console.log(`   Found ${assets.length} files`);

const moduleContent = generateModule(assets);
fs.writeFileSync(OUTPUT_FILE, moduleContent);

const stats = fs.statSync(OUTPUT_FILE);
console.log(`   Generated ${OUTPUT_FILE}`);
console.log(`   Size: ${(stats.size / 1024).toFixed(1)} KB`);
console.log('✅ Done');
